baseURL: 'https://geovane.dev/'
languageCode: 'pt-br'
title: 'Geovane Cavalcante'
theme: 'stack'

menu:
  main:
    - identifier: 'home'
      name: 'Home'
      url: '/'
      weight: 10
    - identifier: 'posts'
      name: 'Postagens'
      url: '/posts/'
      weight: 20
    - identifier: 'talks'
      name: 'Palestras'
      url: '/talks/'
      weight: 25
    - identifier: 'about'
      name: 'Sobre'
      url: '/about/'
      weight: 30

params:
  mainSections: ['posts', 'talks']
  description: 'Blog pessoal de Geovane'
  
  sidebar:
    compact: false
    emoji: 'ğŸ‘¨â€ğŸ’»'
    subtitle: 'Engenheiro de Software'

  comments:
    enabled: true
    provider: giscus
    giscus:
      repo: geovanecavalcante/geovane-blog
      repoId: # VocÃª precisa preencher isso
      category: Comments
      categoryId: # VocÃª precisa preencher isso
      mapping: pathname
      reactionsEnabled: 1
      emitMetadata: 0
      inputPosition: top
      lang: pt

  footer:
    since: 2024

  dateFormat:
    published: 'Jan 02, 2006'
    lastUpdated: 'Jan 02, 2006 15:04 MST' 